<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RootNamespace>core</RootNamespace>
		<AssemblyName>core</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="appsettings.dev.json" />
		<None Remove="appsettings.hml.json" />
		<None Remove="appsettings.json" />
		<None Remove="appsettings.prd.json" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="appsettings.dev.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<DependentUpon>appsettings.json</DependentUpon>
		</Content>
		<Content Include="appsettings.hml.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<DependentUpon>appsettings.json</DependentUpon>
		</Content>
		<Content Include="appsettings.prd.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<DependentUpon>appsettings.json</DependentUpon>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.7.3" />
		<PackageReference Include="Amazon.Lambda.Core" Version="2.8.1" />
		<PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.5" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="Dapper" Version="2.1.66" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
		<PackageReference Include="MySqlConnector" Version="2.3.7" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.6.0" />
	</ItemGroup>
</Project>
