[mysqld]
basedir=C:/workspace/fullstack/OrcaZap/mysql-server
datadir=C:/workspace/fullstack/OrcaZap/mysql-server/data
port=3306
socket=C:/workspace/fullstack/OrcaZap/mysql-server/mysql.sock
log-error=C:/workspace/fullstack/OrcaZap/mysql-server/logs/error.log
bind-address=127.0.0.1
