AWSTemplateFormatVersion: '2010-09-09'
Description: OrcaZap - recursos AWS de produção (stub inicial)

Parameters:
  EnvAlias:
    Type: String
    Default: prd

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub role-lambda-orcazap-${EnvAlias}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub orcazap-api-${EnvAlias}
      ProtocolType: HTTP

Outputs:
  HttpApiEndpoint:
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'
